import { SignInButton, useUser, SignOutButton } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";
import type {RouterOutputs} from "~/utils/api"

import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime"
import Image from 'next/image';
import { LoadingPage } from "../components/loading";
import { useState } from "react";

dayjs.extend(relativeTime);

const CreatePostWizard = () => {
  const {user} = useUser();
  const [input, setInput] = useState("")

  const ctx = api.useContext();

  const {mutate, isLoading: isPosting} = api.posts.create.useMutation({
    onSuccess: () => {
      setInput("");
      ctx.posts.getAll.invalidate();
    
    }
  });
  

  console.log(user)

  if (!user) return null;

  return (
  <div className="flex gap-3 w-full">
    <Link href="/upload">
    <Image src={user.profileImageUrl} 
    className="w-14 h-14 rounded-full"
    alt="your profilr picture"
    width={56}
    height={56}
    /></Link>
    <input placeholder="Type some emojis!" 
    className="grow bg-transparent outline-none"
    type="text"
    value={input}
    onChange={(e) => setInput(e.target.value)}
    disabled={isPosting}
    />
    <button onClick={() => void mutate({ content: input})}>Post</button>

  </div>)
}


type PostWithUser = RouterOutputs["posts"]["getAll"][number];
const PostView = (props: PostWithUser) => {
  const {post, author} = props;
return (
  <div className="p-4 border-b border-slate-400 flex gap-3" 
          key={post.id}>
            <Image src={author.profileImageUrl} className="w-14 h-14 rounded-full" 
            alt={`@${author.username ?? 'unknown'}'s Profile Picture`}
            width={56}
            height={56}
            />
            <div className="flex flex-col">
              <div className="flex text-slate-300 gap-1"> <span >{`@${author.username ?? 'unknown'}`} </span>
              
               <span className="font-thin">{` · ${dayjs(
                post.createdAt 
                ).fromNow()}`}</span> 
                </div>
              <span className="text-xl">{post.content}</span>
              </div>
            </div>
)
}

const Feed = () => {
  const {data, isLoading: postsLoading} = api.posts.getAll.useQuery()

  if (postsLoading) return <LoadingPage/>

  if (!data) return <div>Something went wrong!</div>

  return (
<div className="flex flex-col">
          {data.map((fullPost) => (
            <PostView {...fullPost} key={fullPost.post.id} />
          ))}
        </div>
  )
}

const Home: NextPage = () => {
  const { isLoaded: userLoaded, isSignedIn} = useUser();


  if (!userLoaded) return <div/>

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className="h-full w-full border-slate-400  md:max-w-2xl border-x">
          <div className="border-b border-slate-400 p-4 flex ">
          {!isSignedIn && (
          <div className="flex justify-center">
            <SignInButton />
            </div>
            )}
          {isSignedIn && <CreatePostWizard/>}
        </div>
        <div>
        <Feed/>
        </div>
        <SignOutButton/>
        </div>
      </main>
    </>
  );
};

export default Home;
