import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { SignInButton, useUser, SignOutButton } from "@clerk/nextjs";

import { api } from "~/utils/api";

const CreatePostWizard = () => {
  const {user} = useUser();

  console.log(user)

  if (!user) return null;

  return (
  <div className="flex gap-3 w-full">
    <img src={user.profileImageUrl} className="w-14 h-14 rounded-full"/>
    <input placeholder="Type some emojis!" className="grow bg-transparent outline-none"/>
  </div>)
}

const Home: NextPage = () => {
  const user = useUser();

  const {data, isLoading} = api.posts.getAll.useQuery();

  if (isLoading) return <div>Loading ...</div>

  if (!data) return <div>Something went wrong</div>

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className="h-full w-full border-slate-400  md:max-w-2xl border-x">
          <div className="border-b border-slate-400 p-4 flex ">
          {!user.isSignedIn && (
          <div className="flex justify-center">
            <SignInButton />
            </div>
            )}
          {user.isSignedIn && <CreatePostWizard/>}
        </div>
        <div className="flex flex-col">
          {data?.map((post) => (<div className="p-8 border-b border-slate-400" key={post.id}>{post.content}</div>))}
        </div></div>
      </main>
    </>
  );
};

export default Home;
