import {  useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

// import { api } from "~/utils/api";
// import type {RouterOutputs} from "~/utils/api"

import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime"
// import Image from 'next/image';
// import { LoadingPage } from "../components/loading";
// import { useState } from "react";

dayjs.extend(relativeTime);


// Main home page 
const Home: NextPage = () => {
  


  // const getUser = api.findUser.getUser.useQuery(); 
  
  
  return (
    <>
      <Head>
        <title>Dacreed Interns</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#f3f0f7] to-[#303F9F]">

        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-bold tracking-tight text-[#303F9F] sm:text-[5rem]">
            Welcome to Dacreed User Content Prototype
          </h1>

          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="/prototype1/fileupload"
              target="_blank"
            >
              <h2 className="text-2xl font-bold text-[white]">Prototype 1</h2>
            
              <div className="text-lg">
                Proceed to Content Creation page
              </div>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="/prototype2/upload"
            >
              <h2 className="text-2xl font-bold text-[white]">Prototype 2</h2>
            
              <div className="text-lg">
                Proceed to Content Creation page
              </div>
            </Link>
            <div>

            </div>
          </div>

        </div>
      </main>
    </>
  );
};

export default Home;
