import { type NextPage } from "next"; 
import Head from "next/head"; 
import { api } from "~/utils/api"; 
import { useForm } from "react-hook-form";
import { useRouter } from "next/router";

type UserInfo = {
    name: string; 
}


const UserInfo: NextPage = () => {
    
    const findAllUsers = api.findUsers.getUsers.useQuery()
    
    if (findAllUsers.data === undefined){
        return <div>loading..</div>
    } 


return (
    <>
        <Head>
            <title>Enter Your Name</title>
            <meta name="description" content="Generated by create-t3-app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="flex min-h-screen flex-col items-center justify-center bg-indigo-50]">
            <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
            <h1 className="text-5xl font-extrabold tracking-tight text-[#2e026d] sm:text-[5rem]">
                Hello {findAllUsers.data?.map(user => <div>{user.username}</div>)}
            </h1>
        
            
            </div>
        </main>
    </>
)}

export default UserInfo; 